version: '3.9'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      SQLALCHEMY_DATABASE_URI: postgres://carve:12345@db/dbtest

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: carve
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: dbtest
    ports:
      - "5432:5432"
